import checkoutFormModel from './checkoutFormModel';
const {
  formField: {
    Email,
    Password,
    ConfirmPassword,
    FindUs,
    Name,
    PhoneNo,
    Address,
    Nationality,
    EmergencyContact,
    EmergencyRelationship,
    EmergencyPhone,
    Occupation,
    YearOfExperience,
    Experience,
    HighestTeachingLevel,
    EducatoionLevel,
    Notes,
    SecondarySchool,
    PrimarySchool,
    SchoolCat,
    PublicExamGrade,
    University,
    Major,
    OtherCert,
    Year,
    country,
    agreeWith,
    nameOnCard,
    cardNumber,
    expiryDate,
    cvv
  }
} = checkoutFormModel;

export default {
  [Email.name]: '',
  [Password.name]: '',
  [ConfirmPassword.name]: '',
  [FindUs.name]: '',
  [Name.name]: '',
  [PhoneNo.name]: '',
  [Address.name]: '',
  [Nationality.name]: '',
  [EmergencyContact.name]: '',
  [EmergencyRelationship.name]: '',
  [EmergencyPhone.name]: '',
  [country.name]: '',
  [agreeWith.name]: false,
  [Occupation.name]: '',
  [YearOfExperience.name]: '',
  [Experience.name]: '',
  [HighestTeachingLevel.name]: '',
  [Notes.name]: '',
  [EducatoionLevel.name]: '',
  [SecondarySchool.name]: '',
  [PrimarySchool.name]: '',
  [SchoolCat.name]: '',
  [PublicExamGrade.name]: '',
  [University.name]: '',
  [Major.name]: '',
  [OtherCert.name]: '',
  [Year.name]: '',
  [nameOnCard.name]: '',
  [cardNumber.name]: '',
  [expiryDate.name]: '',
  [cvv.name]: ''
};
